""" This module contains the FastAPI application. It's responsible for 
    creating the FastAPI application and including the routers."""
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
# Import routers
from app.routes.chat_routes import router as chat_routes
from app.routes.pairings_routes import router as pairings_routes
from app.routes.image_routes import router as image_routes
from app.routes.extraction_routes import router as extraction_routes
from app.routes.anthropic_routes import router as anthropic_routes
from app.routes.redis_routes import router as redis_routes


DESCRIPTION = """
# BakespaceAI FastAPI

## Project Overview

BakespaceAI FastAPI is a powerful backend solution designed to provide an array of 
functionality to be integrated with Bakespace website. With this backend, users can 
interact with Large Language Models (LLMs) via several endpoints to personalize their
 culinary experiences.

## Functionality

BakespaceAI FastAPI supports:

**Recipe Generation**: Based on user and system inputs, such as allergies, preferences, and 
cooking skill level, an LLM is leveraged to generate a custom recipe. The output is parsed
into a Pydantic model, ready for downstream use.

**Chat Features**: Post-recipe generation, users can engage in a chat with the LLM about
their recipe. The langchain library provides the chatbot with context for intelligent conversation.

**Recipe Text Extraction**: Users can upload recipes in various formats, including PDF, Word doc, text file, or an
image of a handwritten recipe. These recipes are formatted and can be saved, discussed, or included in cookbooks.

**Image Generation**: Integration with Stability AI's image generation API allows for recipe-based image prompts,
generating unique visuals for each recipe.

**Pairings Generator**: Each recipe can be accompanied by beverage pairings generated by an LLM, 
offering a complete dining experience.

## Dependencies

This project leverages several Python libraries to deliver its functionalities. These include:

*FastAPI* | *Langchain* | *OpenAI* | *Pydantic* | *Python-dotenv* | *Requests* | *Uvicorn* | *Redis*

**FastAPI**: This is a modern, fast (high-performance), web framework for building APIs
with Python 3.6+ based on standard Python type hints.

**Langchain**: A library used to parse and handle natural language text. In this project,
it's used to process and analyze textual data.

**OpenAI**: OpenAI's Python client library, used for interacting with the OpenAI API. It
allows access to powerful AI models for tasks like translation, text completion, and more.

**Pydantic**): A data validation library used to set the data types of incoming request data.
It also provides helpers to convert between types, and to parse complex data structures.

**Python-dotenv**: This library is used to separate secret credentials and your code. It allows
you to add, edit, and load environment variables from .env files.

**Requests**: A simple, yet powerful HTTP library used to send HTTP requests. It abstracts the
complexities of making requests behind a simple API.

**Uvicorn**: An ASGI server that's needed to run your FastAPI applications. It provides
a lightning-fast, asynchronous server for Python applications.

**Redis**: A key-value store used to store session data. It's used to store the session ID

## Installation

To install these dependencies, use 'pip', the Python package installer:

```python
pip install -r requirements.txt
"""



app = FastAPI(
    title="BakeSpace AI",
    description=DESCRIPTION,
    version="0.1",
    summary="Backend to allow BakeSpace users to interact\
            with Large Language Models (LLMs) to personalize\
            their culinary experiences.",
    contact={
        "name": "Dave Thomas",
        "url": "https://enoughwebapp.com",
        "email": "dave_thomas@enoughwebapp.com"
    },
    license_info={
        "name": "MIT License",
        "url": "https://opensource.org/licenses/MIT"
    }
)

# Allow CORS for your front end
app.add_middleware(
    CORSMiddleware,
    allow_origins=['*'],  # Adjust this in production!
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# Include routers
routers = [chat_routes, pairings_routes, image_routes, extraction_routes, anthropic_routes, redis_routes]
for router in routers:
    app.include_router(router)
